#!/bin/bash
set -euo pipefail

#
# SKRules/generate-api.sh — Generate public API docs for a Swift package's CLAUDE.md
#
# Usage:
#   ./generate-api.sh /path/to/Package          # regenerate API section in CLAUDE.md
#   ./generate-api.sh                            # run in current directory
#
# How it works:
#   1. Scans Sources/**/*.swift for public/open declarations
#   2. Groups them by subdirectory (module area)
#   3. Replaces everything between <!-- PUBLIC-API-START --> and <!-- PUBLIC-API-END -->
#      in the package's CLAUDE.md
#
# If CLAUDE.md doesn't have the markers yet, the script appends them.
#
# The generated section is intentionally concise — it lists type signatures and
# method signatures, not full doc comments. This keeps Claude's context lean
# when the package is used as a dependency (not being edited directly).
#

TARGET_DIR="${1:-.}"

if [ ! -d "$TARGET_DIR" ]; then
    echo "Error: Directory '$TARGET_DIR' does not exist."
    exit 1
fi

SOURCES_DIR="$TARGET_DIR/Sources"
CLAUDE_FILE="$TARGET_DIR/CLAUDE.md"

if [ ! -d "$SOURCES_DIR" ]; then
    echo "Error: No Sources/ directory found in '$TARGET_DIR'."
    exit 1
fi

if [ ! -f "$CLAUDE_FILE" ]; then
    echo "Error: No CLAUDE.md found in '$TARGET_DIR'."
    exit 1
fi

# ─── Detect package name from the Sources/ subdirectory ──────────────
PACKAGE_NAME=""
for d in "$SOURCES_DIR"/*/; do
    [ -d "$d" ] || continue
    PACKAGE_NAME="$(basename "$d")"
    break
done

if [ -z "$PACKAGE_NAME" ]; then
    echo "Error: No package directory found under Sources/."
    exit 1
fi

PACKAGE_SOURCES="$SOURCES_DIR/$PACKAGE_NAME"

# ─── Extract public API from Swift files ─────────────────────────────

generate_api_section() {
    echo "## Public API Reference"
    echo ""
    echo "> Auto-generated by \`generate-api.sh\`. Do not edit manually."
    echo ""

    local prev_group=""

    # Find all Swift files under Sources/PackageName, sorted by path
    while IFS= read -r swift_file; do
        local rel_path="${swift_file#"$PACKAGE_SOURCES"/}"
        local filename
        filename="$(basename "$swift_file" .swift)"

        # Determine the group (subdirectory) — e.g. "Storage", "Logger", "Extensions"
        local group
        if [[ "$rel_path" == */* ]]; then
            group="$(dirname "$rel_path" | head -1)"
        else
            group="Root"
        fi

        # Extract public/open declarations
        local declarations
        declarations="$(grep -n '^\s*\(public\|open\)\s' "$swift_file" 2>/dev/null || continue)"

        # Skip files with no public declarations
        [ -z "$declarations" ] && continue

        # Print group header if new group
        if [ "$group" != "$prev_group" ]; then
            [ -n "$prev_group" ] && echo ""
            echo "### $group"
            echo ""
            prev_group="$group"
        fi

        echo "**$filename**"
        echo ""
        echo '```swift'

        # Process each public declaration using process substitution to avoid subshell
        while IFS= read -r line; do
            # Strip line number prefix from grep -n
            local content="${line#*:}"
            # Trim leading whitespace (parameter expansion — no subshell)
            content="${content#"${content%%[![:space:]]*}"}"

            # Skip lines that are just closing braces, comments, or attributes
            case "$content" in
                public\ var\ body*) continue ;;  # Skip SwiftUI body
            esac

            # Clean up: remove opening braces for one-line display
            content="${content% \{}"

            # For protocol/struct/class/enum — show the declaration line
            # For func/var/let — show the signature
            echo "$content"
        done < <(echo "$declarations")

        echo '```'
        echo ""
    done < <(find "$PACKAGE_SOURCES" -name "*.swift" -type f | sort)
}

# ─── Build the replacement block ─────────────────────────────────────

START_MARKER="<!-- PUBLIC-API-START -->"
END_MARKER="<!-- PUBLIC-API-END -->"

API_CONTENT="$(generate_api_section)"

# ─── Inject into CLAUDE.md ───────────────────────────────────────────

if grep -q "$START_MARKER" "$CLAUDE_FILE"; then
    # Markers exist — replace content between them
    # Write API content to temp file to avoid awk escaping issues
    API_TMPFILE=$(mktemp)
    trap 'rm -f "$API_TMPFILE"' EXIT
    echo "$API_CONTENT" > "$API_TMPFILE"

    # Use awk with file reading instead of variable interpolation
    awk -v marker_start="$START_MARKER" -v marker_end="$END_MARKER" -v tmpfile="$API_TMPFILE" '
        $0 == marker_start { print; while ((getline line < tmpfile) > 0) print line; skip=1; next }
        $0 == marker_end { skip=0; print; next }
        !skip { print }
    ' "$CLAUDE_FILE" > "${CLAUDE_FILE}.tmp" && mv "${CLAUDE_FILE}.tmp" "$CLAUDE_FILE"
    echo "Updated public API section in $CLAUDE_FILE"
else
    # No markers — append them at the end
    {
        echo ""
        echo "$START_MARKER"
        echo "$API_CONTENT"
        echo "$END_MARKER"
    } >> "$CLAUDE_FILE"
    echo "Appended public API section to $CLAUDE_FILE"
fi

# ─── Summary ─────────────────────────────────────────────────────────

type_count="$(echo "$API_CONTENT" | grep -c '^\*\*' || true)"
echo "   Package: $PACKAGE_NAME"
echo "   Types documented: $type_count"
